# Generated by Django 2.1.7 on 2019-03-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'UserInfo'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nicheng',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
